### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by Seanmclem** [minhtet-BeeComTech/native-solid#1]
The readme has no real description on what this library really is. What is it?

**Comment by minhtet-BeeComTech** [comment]
> The readme has no real description on what this library really is. What is it?

This package is still under development. So there are no specific documents yet. I'm trying to make specific docs and a good package.

**Comment by Seanmclem** [comment]
> > The readme has no real description on what this library really is. What is it?
> 
> 
> 
> This package is still under development. So there are no specific documents yet. I'm trying to make specific docs and a good package. 

Still, what is it? What might it one day be?
